#!/bin/bash

required_ubuntu_version="16.04"
ros_version="kinetic"
repo_root=$(pwd)
cd ../../../
oars_root=$(pwd)
cd repo_root
opencv_version="3.4.3"

# Check that we're on Ubuntu 16.04
ubuntu_version=$(lsb_release -r | tail -c 6)
if [[ "$ubuntu_version" != "$required_ubuntu_version" ]]
then
  echo "Sorry, Ubuntu 16.04 (xenial) is the only version of Ubuntu supported by this setup script."
  exit
fi

##### Update all system packages first #####

echo Updating system packages...
sudo apt update
sudo apt upgrade

##### INSTALL ROS #####

# Add the apt repo and ROS public key
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt -y install dirmngr
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
sudo apt update

# Install ROS
echo Installing ROS Kinetic...
sudo apt -y install ros-kinetic-desktop-full

# Initialize rosdep
echo Initializing rosdep...
sudo rosdep init
rosdep update

##### INSTALL PYTHON PACKAGES #####
echo Setting up Python to work with ROS...

# Make sure pip is installed
sudo apt -y install python-pip python-dev build-essential
sudo -H pip install --upgrade python pip virtualenv

# Install ROS Python packages (for all Python 2 interpreters)
sudo apt -y install python-rosinstall python-rosinstall-generator python-wstool build-essential

# Make a virtual Python environment
mkdir ../../.virtualenvs/
virtualenv -p python2.7 --system-site-packages $oars_root/.virtualenvs/oars

# Load the ROS environment variables when using the virtual environment
echo "source /opt/ros/$ros_version/setup.bash" >> $oars_root/.virtualenvs/oars/bin/activate

# Add the repo to the Python interpreter path so it can find the Python modules we make
echo "export PYTHONPATH=\$PYTHONPATH:$(pwd)" >> $oars_root/.virtualenvs/oars/bin/activate

# Add a shortcut to activate the virtual environment
venv_activate=$oars_root/.virtualenvs/oars/bin/activate
echo "alias useoars=\"source $venv_activate\"" >> $HOME/.bashrc

# Load all environment variables, aliases, etc
source $HOME/.bashrc
echo Loading virtual Python environment...
source $venv_activate

# Make sure pip is up to date
pip install --upgrade pip

# Install Python dependencies
echo Installing Python requirements...
pip install -r requirements.txt

echo Python configuration complete

##### BUILD THE CATKIN WORKSPACE #####

echo Building the catkin workspace...

cd $repo_root/../..  # cd to catkin_ws, or whatever it's called
catkin_make

# Load the catkin workspace stuff when loading the virtual environment
echo "source $(pwd)/devel/setup.bash" >> .virtualenvs/oars/bin/activate

# Load all environment variables, aliases, etc
source $venv_activate

echo ROS installation complete

##### INSTALL PYCHARM #####

# Check if the user would like to install PyCharm or configure an existing
# installation for ROS
echo
echo
echo "__________        _________ .__"
echo "\______   \___.__.\_   ___ \|  |__ _____ _______  _____"
echo "|     ___<   |  |/    \  \/|  |  \\__  \\_  __ \/     \\"
echo "|    |    \___  |\     \___|   Y  \/ __ \|  | \/  Y Y  \\"
echo "|____|    / ____| \______  /___|  (____  /__|  |__|_|  /"
echo "           \/             \/     \/     \/            \/"
echo
echo
echo "PyCharm is a wonderful integrated development environment \(IDE\) with a built-in code editor and debugger, the latter being a feature a simple debugger like Atom or Sublime does not have. It is highly recommended you install PyCharm to aid with debugging."
echo
answer_valid=false
install_pycharm=false
configure_pycharm_launcher=false
while [ $answer_valid != true ]; do
  echo What would you like to do?
  echo   a\) Install PyCharm and configure with ROS \(recommended\)
  echo   b\) Configure an existing PyCharm installation for use with ROS
  echo   c\) Do nothing related to PyCharm
  echo -n "Your answer: "
  read answer
  if [ $answer == "A" ] || [ $answer == "a" ] || [ "$answer" == "" ]
  then
    answer_valid=true
    install_pycharm=true
    configure_pycharm_launcher=true
  elif [ $answer == "B" ] || [ $answer == "b" ]
  then
    answer_valid=true
    configure_pycharm_launcher=true
  elif [ $answer == "C" ] || [ $answer == "c" ]
  then
    answer_valid=true
  else
    echo Sorry, please enter one of the above options.
    echo
  fi
done

if [ $install_pycharm == true ]
then
  echo
  echo -n "Are you a student? [Y/n] "
  read answer
  if [ $answer == "Y" ] || [ $answer == "y" ] || [ "$answer" == "" ]
  then
    echo Please create an account with JetBrains to get a free copy of PyCharm Professional.
    use_pro=true
    xdg-open https://www.jetbrains.com/student/
    pycharm_version=pycharm-professional
    echo Installing PyCharm Professional...
  else
    pycharm_version=pycharm
    echo Installing PyCharm Community Edition...
  fi
  sudo add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make
  sudo apt update
  sudo apt -y install ubuntu-make
  umake ide $pycharm_version
  echo PyCharm installation complete
fi

if [ $configure_pycharm_launcher == true ]
then
  echo Reconfiguring PyCharm launcher to work with ROS...
  # Launch PyCharm usin bash after loading the virtual environment
  sed -i 's/Exec="/Exec=bash -i -c "useoars \&\& /' $HOME/.local/share/applications/jetbrains-pycharm*.desktop
  echo PyCharm launcher configuration complete
fi

# Install OpenCV, if desired
install_opencv=false
answer_valid=false

while [ $answer_valid != true ]; do
  echo
  echo -n "Would you like to install OpenCV? [Y/n]"
  read answer
  if [ $answer == "Y" ] || [ $answer == "y" ] || [ "$answer" == "" ]
  then
    answer_valid=true
    install_opencv=true
  elif [ $answer == "N" ] || [ $answer == "n" ]
  then
    echo Skipping installation of OpenCV
  fi
done

if [ $install_opencv ]
then
  echo Removing any previous installations of x264...
  sudo apt remove -y x264 libx264-dev
  echo Installing OpenCV dependencies...
  sudo apt install -y checkinstall cmake pkg-config yasm gfortran \
      libjpeg8-dev libjasper-dev libpng12-dev
  sudo apt install -y libtiff5-dev # For Ubuntu 16.04
  sudo apt install -y libavcodec-dev libavformat-dev libswscale-dev \
      libdc1394-22-dev libxine2-dev libv4l-dev libgstreamer0.10-dev \
      libgstreamer-plugins-base0.10-dev qt5-default libgtk2.0-dev libtbb-dev \
      libatlas-base-dev libfaac-dev libmp3lame-dev libtheora-dev libvorbis-dev \
      libxvidcore-dev libopencore-amrnb-dev libopencore-amrwb-dev x264 v4l-utils

  echo Installing necessary Python libraries...
  pip install numpy scipy matplotlib scikit-image scikit-learn ipython

  echo Downloading OpenCV source...
  cd $oars_root
  git clone https://github.com/opencv/opencv.git
  cd opencv
  git checkout $opencv_version

  echo Downloading OpenCV contrib source...
  cd $oars_root
  git clone https://github.com/opencv/opencv_contrib.git
  cd opencv_contrib
  git checkout $opencv_version

  echo Building OpenCV with contrib modules...
  cd ../opencv
  mkdir build
  cd build
  cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
      -D BUILD_EXAMPLES=ON ..
  num_cpu_cores=`nproc`
  make -j$num_cpu_cores
  sudo make install
  sudo sh -c 'echo "/usr/local/lib" >> /etc/ld.so.conf.d/opencv.conf'
  sudo ldconfig
fi

# Install TensorFlow and Keras, if desired
answer_valid=false
while [ $answer_valid != true ]; do
  echo
  echo -n "Would you like to install TensorFlow and Keras? [Y/n] "
  read answer
  if [ $answer == "Y" ] || [ $answer == "y" ] || [ "$answer" == "" ]
  then
    answer_valid=true
    # Install TensorFlow and Keras
    echo Installing TensorFlow and Keras...
    pip install --upgrade matplotlib  # Make sure matplotlib is up to date
    pip install tensorflow keras

    echo TensorFlow and Keras installed successfully in virtual environment.
  elif [ $answer == "N" ] || [ $answer == "n" ]
  then
    echo Skipping installation of TensorFlow and Keras
  fi
done


echo \n\n
echo "Setup complete. Please run the following line to make ROS available in the current terminal window:"
echo
echo "   source ~/.bashrc && source $venv_activate"
echo
echo "Any time you open a new terminal and would like to run ROS commands in it, run the following:"
echo
echo "   useoars"
echo
echo "Enjoy!"
